-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgUzcJhssWBHKBGW51
5ym1Bv3tUoKjTewOdqK3x4e+u82gCgYIKoZIzj0DAQehRANCAASMCtkp9wDmAOib
Ngl4aN1fWbUEmT/iRk7BC8va8zKbYC4KJAPK3yqA6NDVznpaumDIARTPvqWrQ/l3
YQrUc0BI
-----END PRIVATE KEY-----